#!/bin/bash
set -euo pipefail
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

old_domain=$YNH_APP_OLD_DOMAIN
old_path=$YNH_APP_OLD_PATH
new_domain=$YNH_APP_NEW_DOMAIN
new_path=$YNH_APP_NEW_PATH

ynh_script_progression --message="Updating Nginx and SSO permissions..." --weight=2
ynh_change_url_nginx_config

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
app_port=$(ynh_app_setting_get --app=$app --key=app_port)

ynh_add_nginx_config
ynh_systemctl --service nginx --action reload

ynh_script_progression --message="URL change complete." --last
