#!/bin/bash
set -euo pipefail
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME
install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
data_dir=$(ynh_app_setting_get --app=$app --key=data_dir)

ynh_restore --src_path="$install_dir/docker-compose.yml"
ynh_restore --src_path="$data_dir"

if [ -d "$install_dir" ]; then
  pushd "$install_dir" >/dev/null
  docker compose up -d
  popd >/dev/null
fi
